fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

card:
    resource: "@CardBundle/Controller/"
    type:     annotation
    prefix:   /

group:
    resource: "@GroupBundle/Controller/"
    type:     annotation
    prefix:   /

planning:
    resource: "@PlanningBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
