# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    group_service:
        class: GroupBundle\Services\GroupService
        calls:
            - [ setContainer, [ @service_container ] ]

    card_service:
        class: CardBundle\Services\CardService
        calls:
            - [ setContainer, [ @service_container ] ]

    planning_session:
        class: PlanningBundle\Services\PlanningSession
        calls:
            - [ setContainer, [ @service_container ] ]

    session_manager:
        class: PlanningBundle\Services\SessionManager
        calls:
            - [ setContainer, [ @service_container ] ]

    planning_poker.server:
        class: PlanningBundle\RPC\PlanningPokerServer
        calls:
            - [ setContainer, [ @service_container ] ]
        tags:
            - { name: gos_web_socket.rpc }

    planning_poker_revelation.topic:
        arguments:
            - '@session_manager'
        class: PlanningBundle\RPC\RevelationTopic
        tags:
            - { name: gos_web_socket.topic }

    gos_web_socket_server.client_event.listener:
        class: PlanningBundle\RPC\ClientEventListener
        arguments:
            - '@session_manager'
        tags:
            - { name: kernel.event_listener, event: gos_web_socket.client_disconnected, method: onClientDisconnected }