# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    group_service:
        class: GroupBundle\Services\GroupService
        calls:
            - [ setContainer, [ @service_container ] ]

    card_service:
        class: CardBundle\Services\CardService
        calls:
            - [ setContainer, [ @service_container ] ]

    planning_session:
        class: PlanningBundle\Services\PlanningSession
        calls:
            - [ setContainer, [ @service_container ] ]

    session.handler.pdo:
            class:     Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler
            public:    false
            arguments:
                - 'mysql:dbname=planning-poker'
                - { db_username: root, db_password: develop }

    pp.server:
        class: PlanningBundle\RPC\RPCServer
        calls:
            - [ setContainer, [ @service_container ] ]
        tags:
            - { name: gos_web_socket.rpc }